resources:
  - name: github_integration
    type: GitRepo
    configuration:
      gitProvider: github_scm
      path: pipelines61/pipelines
      
pipelines:
  - name: accenture_pipelines_working
    steps:
      - name: bash_commands
        type: Bash
        configuration:
          affinityGroup: your_group_name
        execution:
          onStart:
            - echo "onstart"
          onExecute:
            - echo "exccute"
          onSuccess:
            - echo "success"
